/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface OpenApiComponent {
  name: string
  tsType: string
}
export interface SchemaTypeOptions {
  preferUnknownOverAny: boolean
  preferInterfaceOverType: boolean
}
export interface OpenApiPath {
  path: string
  method: string
  queryParameters?: string
  pathParameters?: string
  requestBody?: string
  responses: Record<string, string>
}
export interface OpenApiParameter {
  description?: string
  required: boolean
  tsType: string
}
export interface OpenApiOutput {
  paths: Array<OpenApiPath>
  components: Array<OpenApiComponent>
}
export declare function openApiToTypes(openApiInput: object): OpenApiOutput
export declare function schemaToType(name: string, schemaInput: object, options?: SchemaTypeOptions | undefined | null): string
