/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface SchemaTypeConfig {
  preferUnknownOverAny: boolean
  preferInterfaceOverType: boolean
}
export declare function schemaToType(name: string, schemaInput: object, config?: SchemaTypeConfig | undefined | null): string
