/* auto-generated by NAPI-RS */
/* eslint-disable */
export interface OpenApiComponent {
  name: string
  tsType: string
}

export interface OpenApiComponent {
  name: string
  tsType: string
}

export interface OpenApiOutput {
  paths: Array<OpenApiPath>
  components: Array<OpenApiComponent>
}

export interface OpenApiOutput {
  paths: Array<OpenApiPath>
  components: Array<OpenApiComponent>
}

export interface OpenApiParameter {
  description?: string
  required: boolean
  tsType: string
}

export interface OpenApiParameter {
  description?: string
  required: boolean
  tsType: string
}

export interface OpenApiPath {
  path: string
  method: string
  queryParameters?: string
  pathParameters?: string
  requestBody?: string
  responses: Record<string, string>
}

export interface OpenApiPath {
  path: string
  method: string
  queryParameters?: string
  pathParameters?: string
  requestBody?: string
  responses: Record<string, string>
}

export declare export declare function openApiToTypes(openApiInput: object): OpenApiOutput

export declare export declare function schemaToType(schemaInput: object, options?: SchemaTypeOptions | undefined | null): string

export interface SchemaTypeOptions {
  name?: string
  preferUnknownOverAny?: boolean
  preferInterfaceOverType?: boolean
}
