import test from 'ava'
import { openApiToTypes } from '../../index.js'

/**
 * These tests only verify that the binary and the `index.js` file generated by Napi are working correctly in Node
 */

test('basic openapi input', (t) => {
  const openapi = {
    openapi: '3.0.0',
    info: {
      title: 'Test API',
      version: '1.0.0',
    },
    paths: {
      '/users': {
        get: {
          responses: {
            '200': {
              description: 'Success response',
              content: {
                'application/json': {
                  schema: {
                    type: 'object',
                    properties: {
                      id: { type: 'string' },
                      name: { type: 'string' },
                      age: { type: 'number' },
                    },
                  },
                },
              },
            },
          },
        },
        post: {
          requestBody: {
            content: {
              'application/json': {
                schema: {
                  $ref: '#/components/schemas/User',
                },
              },
            },
          },
          responses: {
            '201': {
              description: 'User created successfully',
            },
          },
        },
      },
    },
    components: {
      schemas: {
        User: {
          type: 'object',
          properties: {
            id: { type: 'string' },
            name: { type: 'string' },
            age: { type: 'number' },
          },
        },
      },
    },
  }

  const result = openApiToTypes(openapi)
  t.snapshot(result)
})
