import test from 'ava'
import { schemaToTypescript } from '../../index.js'

/**
 * This is the only test because all other tests are in json_schema_to_typescript.rs
 * This test only verifies that the binary and the index.js file generated by napi is working correctly by testing a basic case
 */
test('basic object schema to typescript', (t) => {
  const schema = {
    type: 'object',
    properties: {
      id: { type: 'string' },
      title: { type: 'string' },
      author: { type: 'string' },
      publishedDate: { type: 'string', format: 'date' },
      rating: { type: 'number', format: 'float' },
      age: { type: 'integer' },
    },
  }

  const result = schemaToTypescript('Book', schema)
  t.snapshot(result)
})
