import test from 'ava'
import { schemaToType } from '../../index.js'

/**
 * These tests only verify that the binary and the `index.js` file generated by Napi are working correctly in Node
 */

test('basic object schema', (t) => {
  const schema = {
    type: 'object',
    properties: {
      id: { type: 'string' },
      title: { type: 'string' },
      author: { type: 'string' },
      publishedDate: { type: 'string', format: 'date' },
      rating: { type: 'number', format: 'float' },
      age: { type: 'integer' },
    },
  }

  const result = schemaToType('Book', schema)
  t.snapshot(result)
})


test('prefer interface over type for simple object', (t) => {
  const schema = {
    type: 'object',
    properties: {
      name: { type: 'string' },
      age: { type: 'number' }
    }
  }

  const options = {
    preferUnknownOverAny: false,
    preferInterfaceOverType: true
  }

  const result = schemaToType('Person', schema, options)
  t.snapshot(result)
})

test('schema with unknown types', (t) => {
  const schema = {
    type: 'object',
    properties: {
      id: {
        type: 'string'
      },
      dynamicValue: {},
      arrayOfAny: {
        type: 'array',
        items: {}
      },
      objectWithAny: {
        type: 'object',
        properties: {
          anyProp: {}
        }
      }
    },
    required: ['id']
  }

  const options = {
    preferUnknownOverAny: true,
    preferInterfaceOverType: false
  }

  const result = schemaToType('SchemaWithUnknown', schema, options)
  t.snapshot(result)
})